export const skills = [
    "Game Development", 
    "Voice Over", 
    "Design", 
    "IOS Developer", 
    "UX Writing", 
    "Advertising", 
    "Front-end", 
    "Digital Marketing", 
    "Illustration", 
    "Technology", 
    "Digital Product", 
    "Babysitter", 
    "Photographer",
    "UX Design",
    "UX Research",
    "Sales",
    "Business Development",
    "Accounting",
    "Finance",
    "Data Science",
    "Data Analysis",
]