/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://y67aikijobaxlccvca7rwhflru.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-4v6fbmu2x5ay7pbtcs3ssstggq",
    "aws_cognito_identity_pool_id": "us-east-1:77a58037-1e22-4d04-a3fe-8a335d4ab1bd",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_kj6x2qI4M",
    "aws_user_pools_web_client_id": "34du5ovpi4psiuv9vrh78nj6gf",
    "oauth": {
        "domain": "rr26t1ocfab9-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "freelafinder://",
        "redirectSignOut": "freelafinder://",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [
        "FACEBOOK",
        "GOOGLE"
    ],
    "aws_cognito_signup_attributes": [],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "ffffreelafinderfiles232840-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
