/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://5kbe4a3mpjbwbp5up5rgzfazia.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-4v2enyeqo5dptl2e7shwxbvewa",
    "aws_cognito_identity_pool_id": "us-east-1:8093b5cb-ed98-4b1e-90ca-2ce59eff7a48",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_fhWJpdQQZ",
    "aws_user_pools_web_client_id": "73dj17bv2879fm0lec40qq6d78",
    "oauth": {
        "domain": "rr26t1ocfab9-staging.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "freelafinder://",
        "redirectSignOut": "freelafinder://",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [
        "FACEBOOK",
        "GOOGLE"
    ],
    "aws_cognito_signup_attributes": [],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "ffffreelafinderfiles152020-staging",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
